### ISSUE TITLE
Binary Storage MinIO/S3 -- Bucket Name prefix?

### ISSUE THREAD

**Issue by thunder-spb** [reportportal/kubernetes#115]
HI again,

Is it possible to set some prefix to created buckets?

currently RP creates following:
```
[2020-04-13 12:55:26 UTC]      0B prj-keystore/
[2020-04-13 12:55:49 UTC]      0B prj-users/
```
Or even better to put those under some already created bucket?

Thanks in advance,
A

**Comment by thunder-spb** [comment]
Also would be great to have a list of all bucket names if some others could be created during any actions...

**Comment by AlehB** [comment]
Hi @HardNorth , @Yumfriez ,

Could you please assist?

**Comment by thunder-spb** [comment]
Any updates?

**Comment by gjacquetupgrade** [comment]
I am also looking forward to this.
We were trying to use minio as a S3 gateway but since the bucket names are pretty much hardcoded that won't work as bucket names are global throughout AWS.
Those buckets have already been created under someone else's account.
We would like to be able to use our own.

**Comment by thunder-spb** [comment]
Faced another issue which is related to this: https://github.com/reportportal/service-api/issues/1196

So maybe it worth to copy this issue into service-api since that service has those values hardcoded :(

**Comment by HardNorth** [comment]
@thunder-spb well, as the first step service-api devs need to add ability to configure such prefix / bucket name, then we need to update our department template.

**Comment by thunder-spb** [comment]
thanks @HardNorth for reply. Will this be added to your queue? :) if so, are there any estimates on this?

**Comment by thunder-spb** [comment]
@HardNorth could you please review PRs?

**Comment by pbortnik** [comment]
Hi guys, check out the new [release](https://github.com/reportportal/reportportal) with availability to change bucket prefix via env variables.
Please, give us feedback, so we can close the issue.

**Comment by thunder-spb** [comment]
Thanks, we'll try this on monday.

**Comment by pbortnik** [comment]
@thunder-spb hi, have you tried the new release ?

**Comment by pbortnik** [comment]
@thunder-spb Can i close the issue?

**Comment by apjneeraj** [comment]
@pbortnik :  I tried setting the defaultBucketName and bucketPrefix through env var for service-api and authorization service but it did not work for me.

I set the bucket info like this in pod env var in kubernetes manifest.
```           
            - name: RP_BINARYSTORE_MINIO_BUCKETPREFIX
              value: "nm"
            - name: RP_BINARYSTORE_MINIO_DEFAULTBUCKETNAME
              value: "nmishra-minio" 
```

But I still get access denied error in service-api logs while it try to create keystore/secret-integration-salt' object.

Error:
```
2020-06-17 07:08:14.086 ERROR 8 --- [           main] c.e.t.r.f.d.minio.MinioDataStore         : Unable to find file 'keystore/secret-integration-salt'

2020-06-17 07:08:14.086 ERROR 8 --- [           main] c.e.t.r.f.d.minio.MinioDataStore         : Unable to find file 'keystore/secret-integration-salt'

io.minio.errors.ErrorResponseException: The specified key does not exist.
	at io.minio.MinioClient.executeReq(MinioClient.java:1220)
	at io.minio.MinioClient.execute(MinioClient.java:1082)
	at io.minio.MinioClient.executeGet(MinioClient.java:1339)
	at io.minio.MinioClient.getObject(MinioClient.java:1854)
	at io.minio.MinioClient.getObject(MinioClient.java:1647)
	at com.epam.ta.reportportal.filesystem.distributed.minio.MinioDataStore.load(MinioDataStore.java:83)

---
---
	at com.epam.ta.reportportal.config.EncryptConfiguration.loadOrGenerateIntegrationSalt(EncryptConfiguration.java:93)
	at com.epam.ta.reportportal.config.EncryptConfiguration.afterPropertiesSet(EncryptConfiguration.java:88)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1855)
2020-06-17 07:08:14.374 ERROR 8 --- [           main] c.e.t.r.f.d.minio.MinioDataStore         : Unable to save file 'keystore/secret-integration-salt'
io.minio.errors.ErrorResponseException: Access Denied.
	at io.minio.MinioClient.executeReq(MinioClient.java:1220)
	at io.minio.MinioClient.execute(MinioClient.java:1082)
	at io.minio.MinioClient.executePut(MinioClient.java:1446)
	at io.minio.MinioClient.makeBucket(MinioClient.java:3744)
	at io.minio.MinioClient.makeBucket(MinioClient.java:3650)
	at com.epam.ta.reportportal.filesystem.distributed.minio.MinioDataStore.save(MinioDataStore.java:64)
	at com.epam.ta.reportportal.config.EncryptConfiguration.loadOrGenerateIntegrationSalt(EncryptConfiguration.java:99)
	at com.epam.ta.reportportal.config.EncryptConfiguration.afterPropertiesSet(EncryptConfiguration.java:88)
``` 
Not sure if I am missing anything here?
