### ISSUE TITLE
ReportPortalExceptionResolver > Launch 'null' not found. Did you use correct Launch ID?

### ISSUE THREAD

**Issue by Ngaur** [reportportal/kubernetes#152]
Reportportal is deployed via kubernetes v5 chart.
We are using multiple integrations to this server -- python-client, soapUI client, and java client. 
And suddenly all the integrations are breaking.
Error details : 
`2020-12-03 04:29:30.499 ERROR 7 --- [o-8585-exec-206] .t.r.c.e.r.ReportPortalExceptionResolver : ReportPortalExceptionResolver > Launch 'null' not found. Did you use correct Launch ID?

com.epam.ta.reportportal.exception.ReportPortalException: Launch 'null' not found. Did you use correct Launch ID?
	at com.epam.ta.reportportal.core.log.impl.CreateLogHandlerImpl.lambda$createLog$0(CreateLogHandlerImpl.java:95)
	at java.base/java.util.Optional.orElseThrow(Unknown Source)
	at com.epam.ta.reportportal.core.log.impl.CreateLogHandlerImpl.createLog(CreateLogHandlerImpl.java:95)
	at com.epam.ta.reportportal.core.log.impl.CreateLogHandlerImpl$$FastClassBySpringCGLIB$$1c35ca0e.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:769)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:366)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:99)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
	at com.epam.ta.reportportal.core.log.impl.CreateLogHandlerImpl$$EnhancerBySpringCGLIB$$8d2302d5.createLog(<generated>)
	at com.epam.ta.reportportal.ws.controller.LogController.createLog(LogController.java:101)
	at com.epam.ta.reportportal.ws.controller.LogController$$FastClassBySpringCGLIB$$f7673969.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:769)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:69)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
	at com.epam.ta.reportportal.ws.controller.LogController$$EnhancerBySpringCGLIB$$1da3b675.createLog(<generated>)
	at jdk.internal.reflect.GeneratedMethodAccessor940.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)
`

**Comment by Ngaur** [comment]
Also this one-- 
2020-12-03 04:58:55.731 DEBUG 7 --- [TaskExecutor-87] c.e.t.r.w.rabbit.AsyncReportingListener  : exception : com.epam.ta.reportportal.exception.ReportPortalException, message : Test Item '7f996775-5bfa-4aa1-89e1-ce0630b79077' not found. Did you use correct Test Item ID?,  cause : 
2020-12-03 04:58:55.731  WARN 7 --- [TaskExecutor-87] s.a.r.l.ConditionalRejectingErrorHandler : Execution of Rabbit message listener failed.

org.springframework.amqp.rabbit.support.ListenerExecutionFailedException: Listener threw exception
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.wrapToListenerExecutionFailedExceptionIfNeeded(AbstractMessageListenerContainer.java:1693)
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:1639)
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.actualInvokeListener(AbstractMessageListenerContainer.java:1509)
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:1486)
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:1477)
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.executeListener(AbstractMessageListenerContainer.java:1421)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.doReceiveAndExecute(SimpleMessageListenerContainer.java:963)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.receiveAndExecute(SimpleMessageListenerContainer.java:913)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.access$1600(SimpleMessageListenerContainer.java:81)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.mainLoop(SimpleMessageListenerContainer.java:1284)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.run(SimpleMessageListenerContainer.java:1190)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.springframework.amqp.AmqpRejectAndDontRequeueException: null
	at com.epam.ta.reportportal.ws.rabbit.AsyncReportingListener.onMessage(AsyncReportingListener.java:177)
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:1635)
	... 10 common frames omitted
Caused by: com.epam.ta.reportportal.exception.ReportPortalException: Test Item '7f996775-5bfa-4aa1-89e1-ce0630b79077' not found. Did you use correct Test Item ID?
	at com.epam.ta.reportportal.core.item.impl.FinishTestItemHandlerImpl.lambda$finishTestItem$0(FinishTestItemHandlerImpl.java:142)
	at java.base/java.util.Optional.orElseThrow(Unknown Source)
	at com.epam.ta.reportportal.core.item.impl.FinishTestItemHandlerImpl.finishTestItem(FinishTestItemHandlerImpl.java:142)
	at com.epam.ta.reportportal.core.item.impl.FinishTestItemHandlerImpl$$FastClassBySpringCGLIB$$a8a02107.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:769)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:366)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:99)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
	at com.epam.ta.reportportal.core.item.impl.FinishTestItemHandlerImpl$$EnhancerBySpringCGLIB$$96cfab60.finishTestItem(<generated>)
	at com.epam.ta.reportportal.ws.rabbit.AsyncReportingListener.onFinishItem(AsyncReportingListener.java:204)
	at com.epam.ta.reportportal.ws.rabbit.AsyncReportingListener.onMessage(AsyncReportingListener.java:146)
	... 11 common frames omitted
