### ISSUE TITLE
ReportPortal setup using S3 as datastore throwing InvalidBucketNameException

### ISSUE THREAD

**Issue by mathew-jithinm** [reportportal/kubernetes#247]
**Describe the bug**
Following was the bucket name I used:

`mat-reportportal-store`

I gave the configuration as shown in the document mentioned for Kubernetes installation (Used the access/secret keys and bucket name along with region info) and it throws the following error. Not able to understand the reason for the same as bucket name is correct as per AWS standards.

I have also created a folder `keystore` with the file `secret-integration-salt` in it with a key value to check if that is the issue, but same issue keeps re-occurring. Permissions are all proper.

```
  Scheduler class: 'org.quartz.core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'org.quartz.simpl.SimpleThreadPool' - with 1 threads.
  Using job-store 'org.springframework.scheduling.quartz.LocalDataSourceJobStore' - which supports persistence. and is clustered.

2022-04-13 16:14:00.916  INFO 1 --- [           main] org.quartz.impl.StdSchedulerFactory      : Quartz scheduler 'reportportal' initialized from an externally provided properties instance.
2022-04-13 16:14:00.916  INFO 1 --- [           main] org.quartz.impl.StdSchedulerFactory      : Quartz scheduler version: 2.3.2
2022-04-13 16:14:00.916  INFO 1 --- [           main] org.quartz.core.QuartzScheduler          : JobFactory set to: com.epam.ta.reportportal.core.configs.SchedulerConfiguration$2@3fb0d9de
2022-04-13 16:14:02.153 ERROR 1 --- [           main] c.e.t.r.f.d.minio.MinioDataStore         : Unable to find file 'keystore/secret-integration-salt'

io.minio.errors.InvalidBucketNameException: bucket name does not follow Amazon S3 standards. For more information refer http://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html
	at io.minio.MinioClient.checkBucketName(MinioClient.java:788)
	at io.minio.MinioClient.createRequest(MinioClient.java:887)
	at io.minio.MinioClient.executeReq(MinioClient.java:1101)
	at io.minio.MinioClient.execute(MinioClient.java:1082)
	at io.minio.MinioClient.executeGet(MinioClient.java:1339)
	at io.minio.MinioClient.getObject(MinioClient.java:1854)
```

Same is the continued log:

```
2022-04-13 16:14:02.226 ERROR 1 --- [           main] c.e.t.r.f.d.minio.MinioDataStore         : Unable to save file 'keystore/secret-integration-salt'

io.minio.errors.InvalidBucketNameException: bucket name does not follow Amazon S3 standards. For more information refer http://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html
	at io.minio.MinioClient.checkBucketName(MinioClient.java:788)
	at io.minio.MinioClient.createRequest(MinioClient.java:887)
	at io.minio.MinioClient.executeReq(MinioClient.java:1101)
	at io.minio.MinioClient.execute(MinioClient.java:1082)
	at io.minio.MinioClient.executeHead(MinioClient.java:1353)
```

**Expected behavior**
ReportPortal - S3 connection should get established with the right S3 config.

**Versions:**
 - 5.6.3

@AlehB @avarabyeu @HardNorth Hope you will please have a check.

**Comment by HardNorth** [comment]
@mathew-jithinm RP uses Minio client ver. `6.0.13`: [as per here](https://github.com/reportportal/commons-dao/blob/e3d92ce977bcb13e204008f24392d8668d3e9bb4/build.gradle#L81). And this version of Minio Client using such pattern to validate bucket name: `^[a-z0-9][a-z0-9.\-]+[a-z0-9]$` ([source code](https://github.com/minio/minio-java/blob/6.0.13/api/src/main/java/io/minio/MinioClient.java#L785)). 

I tested your bucket name, it should work fine: [regex101 test](https://regex101.com/r/UjHkTT/1). So the only possible issue I can see here is that either there are space symbols on start/end of the string either you set the parameter incorrectly. Please check out `values.yaml` file for the correct [bucket name](https://github.com/reportportal/kubernetes/blob/6015df60c088a3c5939e260fff208cfa8f9b9fe1/reportportal/values.yaml#L415).

As for `Unable to save file 'keystore/secret-integration-salt'` I believe this is related to the same configuration issue. RP is unable to create this file due to Minio misconfiguration.
