### ISSUE TITLE
report-portal-jobs pod is restarting 

### ISSUE THREAD

**Issue by Dookiee** [reportportal/kubernetes#305]
Hello hello, 

Report portal-jobs pod is restarting all the time and trying to get the issue found below in the logs,

> org.springframework.web.client.ResourceAccessException: I/O error on PUT request for "http://elasticsearch-master.report-portal.svc.cluster.local:9200/logs-reportportal-5/_bulk": Connection refused (Connection refused); nested exception is java.net.ConnectException: Connection refused (Connection refused)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:785) ~[spring-web-5.3.20.jar!/:5.3.20]
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:711) ~[spring-web-5.3.20.jar!/:5.3.20]
	at org.springframework.web.client.RestTemplate.put(RestTemplate.java:497) ~[spring-web-5.3.20.jar!/:5.3.20]
	at com.epam.reportportal.elastic.SimpleElasticSearchClient.lambda$save$1(SimpleElasticSearchClient.java:64) ~[classes!/:na]
	at java.base/java.util.HashMap.forEach(HashMap.java:1337) ~[na:na]
	at com.epam.reportportal.elastic.SimpleElasticSearchClient.save(SimpleElasticSearchClient.java:63) ~[classes!/:na]
	at com.epam.reportportal.log.LogProcessing.process(LogProcessing.java:33) ~[classes!/:na]
	at com.epam.reportportal.calculation.BatchProcessing.processAndSchedule(BatchProcessing.java:54) ~[classes!/:na]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-5.3.20.jar!/:5.3.20]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:na]
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412) ~[na:na]
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255) ~[na:na]
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237) ~[na:na]
	at java.base/java.net.Socket.connect(Socket.java:609) ~[na:na]
	at java.base/java.net.Socket.connect(Socket.java:558) ~[na:na]
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182) ~[na:na]
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:507) ~[na:na]
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:602) ~[na:na]
	at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:275) ~[na:na]
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:374) ~[na:na]
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:395) ~[na:na]
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1253) ~[na:na]
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187) ~[na:na]
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081) ~[na:na]
	at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1015) ~[na:na]
	at org.springframework.http.client.SimpleBufferingClientHttpRequest.executeInternal(SimpleBufferingClientHttpRequest.java:76) ~[spring-web-5.3.20.jar!/:5.3.20]
	at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48) ~[spring-web-5.3.20.jar!/:5.3.20]
	at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:66) ~[spring-web-5.3.20.jar!/:5.3.20]
	at org.springframework.http.client.InterceptingClientHttpRequest$InterceptingRequestExecution.execute(InterceptingClientHttpRequest.java:109) ~[spring-web-5.3.20.jar!/:5.3.20]
	at org.springframework.http.client.support.BasicAuthenticationInterceptor.intercept(BasicAuthenticationInterceptor.java:79) ~[spring-web-5.3.20.jar!/:5.3.20]
	at org.springframework.http.client.InterceptingClientHttpRequest$InterceptingRequestExecution.execute(InterceptingClientHttpRequest.java:93) ~[spring-web-5.3.20.jar!/:5.3.20]
	at org.springframework.http.client.InterceptingClientHttpRequest.executeInternal(InterceptingClientHttpRequest.java:77) ~[spring-web-5.3.20.jar!/:5.3.20]
	at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48) ~[spring-web-5.3.20.jar!/:5.3.20]
	at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:66) ~[spring-web-5.3.20.jar!/:5.3.20]
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:776) ~[spring-web-5.3.20.jar!/:5.3.20]
	... 14 common frames omitted

there is no index in the elastic search named 'logs-reportportal-5'. Not sure where we lost here!

Thank you!

**Comment by Dookiee** [comment]
Closing this issue since CPU & memory crunch in the cluster caused the pod's restart!
