### ISSUE TITLE
Unable to login to the report portal with default username and password

### ISSUE THREAD

**Issue by nbonagi** [reportportal/kubernetes#310]
Hi Team,

I am facing the Login erros while proving default 
username: default
password: 1q2w3e.

below is the screenshot for your reference

![image](https://github.com/reportportal/kubernetes/assets/136325771/595a7cc6-1e7f-4770-ab4b-ae474b1f8aac)

All my services are in running state in kubernetes clsuter. 

Please find the logs for api and uat here

### uat
```
2023-06-15 05:01:50.296 DEBUG 1 --- [nio-9999-exec-1] o.s.security.web.FilterChainProxy        : Secured GET /health
2023-06-15 05:01:50.297 DEBUG 1 --- [io-9999-exec-10] o.s.security.web.FilterChainProxy        : Securing GET /health
2023-06-15 05:01:50.297 DEBUG 1 --- [io-9999-exec-10] s.s.w.c.SecurityContextPersistenceFilter : Set SecurityContextHolder to empty SecurityContext
2023-06-15 05:01:50.298 DEBUG 1 --- [io-9999-exec-10] o.s.s.w.a.AnonymousAuthenticationFilter  : Set SecurityContextHolder to anonymous SecurityContext
2023-06-15 05:01:50.299 DEBUG 1 --- [io-9999-exec-10] o.s.s.w.a.i.FilterSecurityInterceptor    : Authorized filter invocation [GET /health] with attributes [permitAll]
2023-06-15 05:01:50.299 DEBUG 1 --- [io-9999-exec-10] o.s.security.web.FilterChainProxy        : Secured GET /health
2023-06-15 05:01:50.305 DEBUG 1 --- [io-9999-exec-10] s.s.w.c.SecurityContextPersistenceFilter : Cleared SecurityContextHolder to complete request
2023-06-15 05:01:50.305 DEBUG 1 --- [nio-9999-exec-1] s.s.w.c.SecurityContextPersistenceFilter : Cleared SecurityContextHolder to complete request
2023-06-15 05:02:30.295 DEBUG 1 --- [nio-9999-exec-3] o.s.security.web.FilterChainProxy        : Securing GET /health
2023-06-15 05:02:30.296 DEBUG 1 --- [nio-9999-exec-3] s.s.w.c.SecurityContextPersistenceFilter : Set SecurityContextHolder to empty SecurityContext
2023-06-15 05:02:30.297 DEBUG 1 --- [nio-9999-exec-3] o.s.s.w.a.AnonymousAuthenticationFilter  : Set SecurityContextHolder to anonymous SecurityContext
2023-06-15 05:02:30.297 DEBUG 1 --- [nio-9999-exec-3] o.s.s.w.a.i.FilterSecurityInterceptor    : Authorized filter invocation [GET /health] with attributes [permitAll]
2023-06-15 05:02:30.295 DEBUG 1 --- [nio-9999-exec-2] o.s.security.web.FilterChainProxy        : Securing GET /health
2023-06-15 05:02:30.297 DEBUG 1 --- [nio-9999-exec-3] o.s.security.web.FilterChainProxy        : Secured GET /health
2023-06-15 05:02:30.297 DEBUG 1 --- [nio-9999-exec-2] s.s.w.c.SecurityContextPersistenceFilter : Set SecurityContextHolder to empty SecurityContext
2023-06-15 05:02:30.298 DEBUG 1 --- [nio-9999-exec-2] o.s.s.w.a.AnonymousAuthenticationFilter  : Set SecurityContextHolder to anonymous SecurityContext
2023-06-15 05:02:30.298 DEBUG 1 --- [nio-9999-exec-2] o.s.s.w.a.i.FilterSecurityInterceptor    : Authorized filter invocation [GET /health] with attributes [permitAll]
2023-06-15 05:02:30.298 DEBUG 1 --- [nio-9999-exec-2] o.s.security.web.FilterChainProxy        : Secured GET /health
2023-06-15 05:02:30.306 DEBUG 1 --- [nio-9999-exec-2] s.s.w.c.SecurityContextPersistenceFilter : Cleared SecurityContextHolder to complete request
2023-06-15 05:02:30.306 DEBUG 1 --- [nio-9999-exec-3] s.s.w.c.SecurityContextPersistenceFilter : Cleared SecurityContextHolder to complete request
2023-06-15 05:03:10.295 DEBUG 1 --- [nio-9999-exec-5] o.s.security.web.FilterChainProxy        : Securing GET /health
2023-06-15 05:03:10.295 DEBUG 1 --- [nio-9999-exec-5] s.s.w.c.SecurityContextPersistenceFilter : Set SecurityContextHolder to empty SecurityContext
2023-06-15 05:03:10.295 DEBUG 1 --- [nio-9999-exec-5] o.s.s.w.a.AnonymousAuthenticationFilter  : Set SecurityContextHolder to anonymous SecurityContext
2023-06-15 05:03:10.296 DEBUG 1 --- [nio-9999-exec-5] o.s.s.w.a.i.FilterSecurityInterceptor    : Authorized filter invocation [GET /health] with attributes [permitAll]
2023-06-15 05:03:10.296 DEBUG 1 --- [nio-9999-exec-5] o.s.security.web.FilterChainProxy        : Secured GET /health
2023-06-15 05:03:10.297 DEBUG 1 --- [nio-9999-exec-4] o.s.security.web.FilterChainProxy        : Securing GET /health
2023-06-15 05:03:10.297 DEBUG 1 --- [nio-9999-exec-4] s.s.w.c.SecurityContextPersistenceFilter : Set SecurityContextHolder to empty SecurityContext
2023-06-15 05:03:10.297 DEBUG 1 --- [nio-9999-exec-4] o.s.s.w.a.AnonymousAuthenticationFilter  : Set SecurityContextHolder to anonymous SecurityContext
2023-06-15 05:03:10.297 DEBUG 1 --- [nio-9999-exec-4] o.s.s.w.a.i.FilterSecurityInterceptor    : Authorized filter invocation [GET /health] with attributes [permitAll]
2023-06-15 05:03:10.297 DEBUG 1 --- [nio-9999-exec-4] o.s.security.web.FilterChainProxy        : Secured GET /health
2023-06-15 05:03:10.303 DEBUG 1 --- [nio-9999-exec-5] s.s.w.c.SecurityContextPersistenceFilter : Cleared SecurityContextHolder to complete request
2023-06-15 05:03:10.305 DEBUG 1 --- [nio-9999-exec-4] s.s.w.c.SecurityContextPersistenceFilter : Cleared SecurityContextHolder to complete request
2023-06-15 05:03:50.296 DEBUG 1 --- [nio-9999-exec-6] o.s.security.web.FilterChainProxy        : Securing GET /health
2023-06-15 05:03:50.296 DEBUG 1 --- [nio-9999-exec-8] o.s.security.web.FilterChainProxy        : Securing GET /health
2023-06-15 05:03:50.296 DEBUG 1 --- [nio-9999-exec-8] s.s.w.c.SecurityContextPersistenceFilter : Set SecurityContextHolder to empty SecurityContext
2023-06-15 05:03:50.296 DEBUG 1 --- [nio-9999-exec-6] s.s.w.c.SecurityContextPersistenceFilter : Set SecurityContextHolder to empty SecurityContext
2023-06-15 05:03:50.296 DEBUG 1 --- [nio-9999-exec-6] o.s.s.w.a.AnonymousAuthenticationFilter  : Set SecurityContextHolder to anonymous SecurityContext
2023-06-15 05:03:50.296 DEBUG 1 --- [nio-9999-exec-8] o.s.s.w.a.AnonymousAuthenticationFilter  : Set SecurityContextHolder to anonymous SecurityContext
2023-06-15 05:03:50.297 DEBUG 1 --- [nio-9999-exec-6] o.s.s.w.a.i.FilterSecurityInterceptor    : Authorized filter invocation [GET /health] with attributes [permitAll]
2023-06-15 05:03:50.297 DEBUG 1 --- [nio-9999-exec-6] o.s.security.web.FilterChainProxy        : Secured GET /health
2023-06-15 05:03:50.297 DEBUG 1 --- [nio-9999-exec-8] o.s.s.w.a.i.FilterSecurityInterceptor    : Authorized filter invocation [GET /health] with attributes [permitAll]
2023-06-15 05:03:50.298 DEBUG 1 --- [nio-9999-exec-8] o.s.security.web.FilterChainProxy        : Secured GET /health
2023-06-15 05:03:50.303 DEBUG 1 --- [nio-9999-exec-6] s.s.w.c.SecurityContextPersistenceFilter : Cleared SecurityContextHolder to complete request
2023-06-15 05:03:50.303 DEBUG 1 --- [nio-9999-exec-8] s.s.w.c.SecurityContextPersistenceFilter : Cleared SecurityContextHolder to complete request
2023-06-15 05:04:30.295 DEBUG 1 --- [nio-9999-exec-7] o.s.security.web.FilterChainProxy        : Securing GET /health
2023-06-15 05:04:30.296 DEBUG 1 --- [nio-9999-exec-7] s.s.w.c.SecurityContextPersistenceFilter : Set SecurityContextHolder to empty SecurityContext
2023-06-15 05:04:30.296 DEBUG 1 --- [nio-9999-exec-7] o.s.s.w.a.AnonymousAuthenticationFilter  : Set SecurityContextHolder to anonymous SecurityContext
2023-06-15 05:04:30.296 DEBUG 1 --- [nio-9999-exec-7] o.s.s.w.a.i.FilterSecurityInterceptor    : Authorized filter invocation [GET /health] with attributes [permitAll]
2023-06-15 05:04:30.297 DEBUG 1 --- [nio-9999-exec-7] o.s.security.web.FilterChainProxy        : Secured GET /health
2023-06-15 05:04:30.297 DEBUG 1 --- [nio-9999-exec-9] o.s.security.web.FilterChainProxy        : Securing GET /health
2023-06-15 05:04:30.297 DEBUG 1 --- [nio-9999-exec-9] s.s.w.c.SecurityContextPersistenceFilter : Set SecurityContextHolder to empty SecurityContext
2023-06-15 05:04:30.297 DEBUG 1 --- [nio-9999-exec-9] o.s.s.w.a.AnonymousAuthenticationFilter  : Set SecurityContextHolder to anonymous SecurityContext
2023-06-15 05:04:30.297 DEBUG 1 --- [nio-9999-exec-9] o.s.s.w.a.i.FilterSecurityInterceptor    : Authorized filter invocation [GET /health] with attributes [permitAll]
2023-06-15 05:04:30.297 DEBUG 1 --- [nio-9999-exec-9] o.s.security.web.FilterChainProxy        : Secured GET /health
2023-06-15 05:04:30.303 DEBUG 1 --- [nio-9999-exec-9] s.s.w.c.SecurityContextPersistenceFilter : Cleared SecurityContextHolder to complete request
2023-06-15 05:04:30.310 DEBUG 1 --- [nio-9999-exec-7] s.s.w.c.SecurityContextPersistenceFilter : Cleared SecurityContextHolder to complete request
2023-06-15 05:05:10.296 DEBUG 1 --- [io-9999-exec-10] o.s.security.web.FilterChainProxy        : Securing GET /health
2023-06-15 05:05:10.297 DEBUG 1 --- [io-9999-exec-10] s.s.w.c.SecurityContextPersistenceFilter : Set SecurityContextHolder to empty SecurityContext
2023-06-15 05:05:10.297 DEBUG 1 --- [io-9999-exec-10] o.s.s.w.a.AnonymousAuthenticationFilter  : Set SecurityContextHolder to anonymous SecurityContext
2023-06-15 05:05:10.297 DEBUG 1 --- [io-9999-exec-10] o.s.s.w.a.i.FilterSecurityInterceptor    : Authorized filter invocation [GET /health] with attributes [permitAll]
2023-06-15 05:05:10.297 DEBUG 1 --- [nio-9999-exec-1] o.s.security.web.FilterChainProxy        : Securing GET /health
2023-06-15 05:05:10.297 DEBUG 1 --- [io-9999-exec-10] o.s.security.web.FilterChainProxy        : Secured GET /health
2023-06-15 05:05:10.297 DEBUG 1 --- [nio-9999-exec-1] s.s.w.c.SecurityContextPersistenceFilter : Set SecurityContextHolder to empty SecurityContext
2023-06-15 05:05:10.297 DEBUG 1 --- [nio-9999-exec-1] o.s.s.w.a.AnonymousAuthenticationFilter  : Set SecurityContextHolder to anonymous SecurityContext
2023-06-15 05:05:10.298 DEBUG 1 --- [nio-9999-exec-1] o.s.s.w.a.i.FilterSecurityInterceptor    : Authorized filter invocation [GET /health] with attributes [permitAll]
2023-06-15 05:05:10.298 DEBUG 1 --- [nio-9999-exec-1] o.s.security.web.FilterChainProxy        : Secured GET /health
2023-06-15 05:05:10.307 DEBUG 1 --- [io-9999-exec-10] s.s.w.c.SecurityContextPersistenceFilter : Cleared SecurityContextHolder to complete request
2023-06-15 05:05:10.308 DEBUG 1 --- [nio-9999-exec-1] s.s.w.c.SecurityContextPersistenceFilter : Cleared SecurityContextHolder to complete request
2023-06-15 05:05:50.297 DEBUG 1 --- [nio-9999-exec-2] o.s.security.web.FilterChainProxy        : Securing GET /health
2023-06-15 05:05:50.297 DEBUG 1 --- [nio-9999-exec-2] s.s.w.c.SecurityContextPersistenceFilter : Set SecurityContextHolder to empty SecurityContext
2023-06-15 05:05:50.297 DEBUG 1 --- [nio-9999-exec-2] o.s.s.w.a.AnonymousAuthenticationFilter  : Set SecurityContextHolder to anonymous SecurityContext
2023-06-15 05:05:50.298 DEBUG 1 --- [nio-9999-exec-3] o.s.security.web.FilterChainProxy        : Securing GET /health
2023-06-15 05:05:50.298 DEBUG 1 --- [nio-9999-exec-3] s.s.w.c.SecurityContextPersistenceFilter : Set SecurityContextHolder to empty SecurityContext
2023-06-15 05:05:50.298 DEBUG 1 --- [nio-9999-exec-2] o.s.s.w.a.i.FilterSecurityInterceptor    : Authorized filter invocation [GET /health] with attributes [permitAll]
2023-06-15 05:05:50.298 DEBUG 1 --- [nio-9999-exec-2] o.s.security.web.FilterChainProxy        : Secured GET /health
2023-06-15 05:05:50.298 DEBUG 1 --- [nio-9999-exec-3] o.s.s.w.a.AnonymousAuthenticationFilter  : Set SecurityContextHolder to anonymous SecurityContext
2023-06-15 05:05:50.298 DEBUG 1 --- [nio-9999-exec-3] o.s.s.w.a.i.FilterSecurityInterceptor    : Authorized filter invocation [GET /health] with attributes [permitAll]
2023-06-15 05:05:50.298 DEBUG 1 --- [nio-9999-exec-3] o.s.security.web.FilterChainProxy        : Secured GET /health
2023-06-15 05:05:50.303 DEBUG 1 --- [nio-9999-exec-3] s.s.w.c.SecurityContextPersistenceFilter : Cleared SecurityContextHolder to complete request
2023-06-15 05:05:50.303 DEBUG 1 --- [nio-9999-exec-2] s.s.w.c.SecurityContextPersistenceFilter : Cleared SecurityContextHolder to complete request
```

**API**
```
2023-06-15 04:28:53.014  INFO 1 --- [portal_Worker-1] c.e.t.r.job.CleanExpiredCreationBidsJob  : Cleaning expired user creation bids finished. Deleted 0 bids
2023-06-15 04:28:53.207 ERROR 1 --- [           main] c.e.t.r.f.distributed.s3.S3DataStore     : Unable to find file 'keystore/migration'

java.lang.NullPointerException: null
	at com.epam.ta.reportportal.filesystem.distributed.s3.S3DataStore.load(S3DataStore.java:89)
	at com.epam.ta.reportportal.core.events.handler.IntegrationSecretsMigrationHandler.migrate(IntegrationSecretsMigrationHandler.java:77)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:344)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:229)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:166)
	at com.epam.ta.reportportal.core.events.multicaster.DelegatingApplicationEventMulticaster.doInvokeListener(DelegatingApplicationEventMulticaster.java:59)
	at com.epam.ta.reportportal.core.events.multicaster.DelegatingApplicationEventMulticaster.lambda$invokeListener$2(DelegatingApplicationEventMulticaster.java:50)
	at java.base/java.util.Optional.ifPresentOrElse(Optional.java:203)
	at com.epam.ta.reportportal.core.events.multicaster.DelegatingApplicationEventMulticaster.invokeListener(DelegatingApplicationEventMulticaster.java:44)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:421)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:378)
	at org.springframework.boot.context.event.EventPublishingRunListener.running(EventPublishingRunListener.java:111)
	at org.springframework.boot.SpringApplicationRunListeners.lambda$running$6(SpringApplicationRunListeners.java:79)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:117)
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:111)
	at org.springframework.boot.SpringApplicationRunListeners.running(SpringApplicationRunListeners.java:79)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:354)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1365)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1354)
	at com.epam.ta.reportportal.core.configs.ReportPortalApp.main(ReportPortalApp.java:37)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)

2023-06-15 04:28:53.208  INFO 1 --- [           main] c.e.h.IntegrationSecretsMigrationHandler : Secrets migration is not needed
2023-06-15 04:28:53.325  INFO 1 --- [nio-8585-exec-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
2023-06-15 04:28:53.325  INFO 1 --- [nio-8585-exec-1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2023-06-15 04:28:53.333  INFO 1 --- [nio-8585-exec-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 8 ms
2023-06-15 04:28:53.597  INFO 1 --- [nio-8585-exec-1] o.s.a.r.c.CachingConnectionFactory       : Attempting to connect to: reportporatl-rabbitmq:5672
2023-06-15 04:28:53.606  INFO 1 --- [nio-8585-exec-1] o.s.a.r.c.CachingConnectionFactory       : Created new connection: analyzerConnectionFactory#75882ac2:0/SimpleConnection@6b0ab6dc [delegate=amqp://rabbitmq@192.168.123.40:5672/analyzer, localPort= 52018]
```

I am using minio instead of s3 bucket

please help

**Comment by nbonagi** [comment]
![image](https://github.com/reportportal/kubernetes/assets/136325771/fb92b610-833e-4635-8473-be954acfacde)
 all my pods are running

**Comment by alencarsouza** [comment]
Was that solved? I am also having the same issue.

![Screenshot from 2023-07-24 14-09-41](https://github.com/reportportal/kubernetes/assets/1081329/dfa5a85c-2899-4877-bb70-306de92c9b8c)

**Comment by DzmitryHumianiuk** [comment]
@alencarsouza @nbonagi please check if you have all params added accordingly.
And try the latest updates release today.

Here is the compose for refference:
https://github.com/reportportal/reportportal/blob/master/docker-compose.yml

you may find a ton of changes occurred there: https://github.com/reportportal/reportportal/pull/2098/files

**Comment by DzmitryHumianiuk** [comment]
@nbonagi i see no services on your login screen and under login form.
It should be something similar to what @alencarsouza has here https://github.com/reportportal/kubernetes/issues/310#issuecomment-1647789663

@alencarsouza and you probably missing the updated in healtcheck for the Service-API

**Comment by alencarsouza** [comment]
@DzmitryHumianiuk 
My issue was due the fact that  GCE Ingress controller does not support the `rewrite-target` annotation. This annotation is crucial as it allows us to change the URL path before sending the request to the backend service. As a result of this limitation, the backend services were either giving 404 errors or providing the wrong responses. To solve this problem, I had to set up Nginx ingress with limited scope, focusing only on the 'reportal' namespace. This approach fixed the problem.

**Comment by DzmitryHumianiuk** [comment]
@raikbitters please pay attention to this above. This probably might be a good point for us as well.
