### ISSUE TITLE
service-jobs is sending auth headers to a ES AWS instance without auth in place

### ISSUE THREAD

**Issue by xuoja-acc** [reportportal/kubernetes#315]
Hi,

Starting with the version 5.7.4 with the double-logging enable we have this error our logs : 

```
2023-04-03 14:13:08.202 ERROR 1 --- [pool-6-thread-1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task
org.springframework.web.client.HttpClientErrorException$Forbidden: 403 Forbidden: "{"message":"Authorization header requires 'Credential' parameter. Authorization header requires 'Signature' parameter. Authorization header requires 'SignedHeaders' parameter. Authorization header requires existence of either a 'X-Amz-Date' or a 'Date' header. Authorization=Basic Og=="}"
        at org.springframework.web.client.HttpClientErrorException.create(HttpClientErrorException.java:109) ~[spring-web-5.3.20.jar!/:5.3.20]
        at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:168) ~[spring-web-5.3.20.jar!/:5.3.20]
        at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:122) ~[spring-web-5.3.20.jar!/:5.3.20]
        at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63) ~[spring-web-5.3.20.jar!/:5.3.20]
        at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:819) ~[spring-web-5.3.20.jar!/:5.3.20]
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:777) ~[spring-web-5.3.20.jar!/:5.3.20]
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:711) ~[spring-web-5.3.20.jar!/:5.3.20]
        at org.springframework.web.client.RestTemplate.put(RestTemplate.java:497) ~[spring-web-5.3.20.jar!/:5.3.20]
        at com.epam.reportportal.elastic.SimpleElasticSearchClient.lambda$save$1(SimpleElasticSearchClient.java:64) ~[classes!/:na]
        at java.base/java.util.HashMap.forEach(HashMap.java:1337) ~[na:na]
        at com.epam.reportportal.elastic.SimpleElasticSearchClient.save(SimpleElasticSearchClient.java:63) ~[classes!/:na]
        at com.epam.reportportal.log.LogProcessing.process(LogProcessing.java:33) ~[classes!/:na]
        at com.epam.reportportal.calculation.BatchProcessing.processAndSchedule(BatchProcessing.java:54) ~[classes!/:na]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-5.3.20.jar!/:5.3.20]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]
```

Same as : https://github.com/reportportal/service-auto-analyzer/issues/121

Refers to : https://github.com/reportportal/service-jobs/issues/64

**Comment by hlebkanonik** [comment]
Closing as stale (opened in 2023 or earlier). Please use the [latest Helm chart](https://github.com/reportportal/kubernetes/tree/main/reportportal) and [documentation](https://github.com/reportportal/kubernetes/blob/main/docs/README.md). If this problem persists with the current release, open a new issue with your Helm/Kubernetes versions and relevant logs. Summary of closed issues: [docs/issues-closed-until-2023.md](https://github.com/reportportal/kubernetes/blob/main/docs/issues-closed-until-2023.md).
